In [1]:
%matplotlib inline

In [13]:
import numpy as np
from scipy.stats import dirichlet
np.set_printoptions(precision=2)

def stats(scale_factor, G0=[.1, .1, .3], N=10000):
    print scale_factor*np.array(G0)
    samples = dirichlet(alpha = scale_factor * np.array(G0)).rvs(N)
    print "                          alpha:", scale_factor
    print "              element-wise mean:", samples.mean(axis=0)
    print "element-wise standard deviation:", samples.std(axis=0)
    print
    
for scale in [0.1, 2, 10, 100, 1000]:
    stats(scale)

[ 0.01  0.01  0.03]
                          alpha: 0.1
              element-wise mean: [ 0.2   0.21  0.59]
element-wise standard deviation: [ 0.39  0.39  0.48]

[ 0.2  0.2  0.6]
                          alpha: 2
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.28  0.28  0.35]

[ 1.  1.  3.]
                          alpha: 10
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.16  0.16  0.2 ]

[ 10.  10.  30.]
                          alpha: 100
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.06  0.06  0.07]

[ 100.  100.  300.]
                          alpha: 1000
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.02  0.02  0.02]



In [3]:
import numpy as np
from scipy.stats import dirichlet
np.set_printoptions(precision=2)

In [7]:
def stats(scale_factor, G0=[.2, .2, .6], N=10000):
    samples = dirichlet(alpha = scale_factor * np.array(G0)).rvs(N)
    print "                          alpha:", scale_factor
    print "              element-wise mean:", samples.mean(axis=0)
    print "element-wise standard deviation:", samples.std(axis=0)
    print

In [9]:
??dirichlet

In [8]:
for scale in [0.1, 1, 10, 100, 1000]:
    stats(scale)

                          alpha: 0.1
              element-wise mean: [ 0.19  0.21  0.6 ]
element-wise standard deviation: [ 0.37  0.38  0.47]

                          alpha: 1
              element-wise mean: [ 0.2   0.21  0.6 ]
element-wise standard deviation: [ 0.28  0.29  0.35]

                          alpha: 10
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.12  0.12  0.15]

                          alpha: 100
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.04  0.04  0.05]

                          alpha: 1000
              element-wise mean: [ 0.2  0.2  0.6]
element-wise standard deviation: [ 0.01  0.01  0.02]

